apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: generic-topology-processor
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: generic-topology-processor
subjects:
- kind: ServiceAccount
  name: generic-topology-processor